### ISSUE TITLE
Support for GFS Data in ocf-data-sampler

### ISSUE THREAD

**Issue by siddharth7113** [openclimatefix/ocf-data-sampler#188]
### **Detailed Description**  
I am trying to use `ocf-data-sampler` to load GFS (Global Forecast System) data using `PVNetUKRegionalDataset`. However, I encountered the following error when specifying `provider: gfs` in my configuration file:

```
ValueError: Unknown provider: gfs
```

It appears that `gfs` is not recognized as a valid provider in `ocf_data_sampler.load.nwp.open_nwp`. I would like to confirm whether `gfs` is expected to be supported, and if not, whether there is a recommended workaround to use GFS data within `ocf-data-sampler`.

### **Implementation Details**  
- **Configuration file snippet:**
  ```yaml
  input_data:
    nwp:
      gfs:
        time_resolution_minutes: 180
        interval_start_minutes: -180
        interval_end_minutes: 540
        max_staleness_minutes: null
        zarr_path: "s3://ocf-open-data-pvnet/data/gfs.zarr"
        provider: "gfs"
        channels:
          - dlwrf
          - dswrf
          - hcc
          - lcc
          - mcc
          - prate
          - r
          - t
          - tcc
          - u10
          - v10
          - vis
  ```
- **Test script:**
  ```python
  from ocf_data_sampler.torch_datasets.pvnet import PVNetUKRegionalDataset

  dataset = PVNetUKRegionalDataset(config_filename="gfs_config.yaml")
  print(len(dataset))
  ```
- **Error message received:**
  ```
  ValueError: Unknown provider: gfs
  ```

### **Question**  
Is there a way to load GFS data using `ocf-data-sampler` as it currently stands, or would modifications be needed to add support for GFS? If modifications are required, what would be the best approach to integrate GFS as a provider?
