### ISSUE TITLE
PVNetUKRegionalDataset Configuration Validation Error

### ISSUE THREAD

**Issue by alirashidAR** [openclimatefix/ocf-data-sampler#196]
### Description  
While creating datasets using `PVNetUKRegionalDataset`, an error occurs during the validation of `config.yaml`.  

### Steps to Reproduce  
Run the following code:  

```python
dataset = PVNetUKRegionalDataset(config_filename=config_file_path, gsp_ids=[0])
```

Use the following `config.yaml`:  

```yaml
general:
  description: Config for accessing Met Office UK Deterministic NWP data
  name: PVNet current (Met Office UK)

input_data:
  gsp:
    dropout_fraction: 0
    dropout_timedeltas_minutes: []
    interval_start_minutes: -120
    interval_end_minutes: 480
    zarr_path: {zarr_path}  # Placeholder to be replaced
    time_resolution_minutes: 30

  nwp:
    ukv:  # Changed from met_office to ukv
      dropout_fraction: 1.0
      dropout_timedeltas_minutes: [-5, -10, -15]
      interval_start_minutes: -120
      interval_end_minutes: 480
      provider: "ukv"  # Changed from met_office to ukv
      zarr_path: {zarr_path}  # Placeholder to be replaced
      channels:
        - t
      image_size_pixels_height: 970
      image_size_pixels_width: 1042
      time_resolution_minutes: 60
```

### Expected Behavior  
The dataset should be created successfully without validation errors.  

### Actual Behavior  
Validation of the `config.yaml` fails, preventing dataset creation.  

```bash
AttributeError                            Traceback (most recent call last)
Cell In[26], line 2
      1 # Load dataset using your configuration file
----> 2 dataset = PVNetUKRegionalDataset(config_filename=config_file_path, gsp_ids=[0])
      4 # Print dataset info
      5 print(f"Dataset length: {len(dataset)}")

File d:\open-source\open-data-research\venv\Lib\site-packages\ocf_data_sampler\torch_datasets\datasets\pvnet_uk.py:192, in PVNetUKRegionalDataset.__init__(self, config_filename, start_time, end_time, gsp_ids)
    190 config: Configuration = load_yaml_configuration(config_filename)
    191 validate_nwp_channels(config)
--> 192 validate_satellite_channels(config)
    194 datasets_dict = get_dataset_dict(config.input_data)
    196 # Get t0 times where all input data is available

File d:\open-source\open-data-research\venv\Lib\site-packages\ocf_data_sampler\torch_datasets\utils\validate_channels.py:78, in validate_satellite_channels(config)
     68 """Validate that satellite channels in config have corresponding normalisation constants.
     69 
     70 Args:
   (...)
     74     ValueError: If there's a mismatch between configured satellite channels and normalisation constants
     75 """
     76 if hasattr(config.input_data, "satellite"):
     77     validate_channels(
---> 78         data_channels=config.input_data.satellite.channels,
...
     80         stds_channels=RSS_STD.channel.values,
     81         source_name="satellite"
     82     )

AttributeError: 'NoneType' object has no attribute 'channels'
```

### Additional Context  
- Ensure the `zarr_path` placeholder is correctly replaced with an actual path.  
- The provider has been changed from `met_office` to `ukv`.
